import { CDN_URL, REPO_REF, REPO_SLUG } from "./constants";
import type { RuleProvider } from "./types";

export const ruleProviders: Record<string, RuleProvider> = {
    ADBlock: {
        type: "http",
        behavior: "domain",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/217heidai/adblockfilters@main/rules/adblockmihomolite.yaml`,
        path: "./ruleset/ADBlock.yaml",
    },
    StaticResources: {
        type: "http",
        behavior: "domain",
        format: "text",
        interval: 86400,
        url: "https://ruleset.skk.moe/Clash/domainset/cdn.txt",
        path: "./ruleset/StaticResources.txt",
    },
    CDNResources: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: "https://ruleset.skk.moe/Clash/non_ip/cdn.txt",
        path: "./ruleset/CDNResources.txt",
    },
    OpenAI: {
        type: "http",
        behavior: "classical",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/VPSDance/ai-proxy-rules@main/rules/clash/openai.yaml`,
        path: "./ruleset/OpenAI.yaml",
    },
    Claude: {
        type: "http",
        behavior: "classical",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/VPSDance/ai-proxy-rules@main/rules/clash/anthropic.yaml`,
        path: "./ruleset/Claude.yaml",
    },
    AICatchAll: {
        type: "http",
        behavior: "classical",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/VPSDance/ai-proxy-rules@main/rules/clash/all.yaml`,
        path: "./ruleset/AICatchAll.yaml",
    },
    TikTok: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/${REPO_SLUG}@${REPO_REF}/ruleset/TikTok.list`,
        path: "./ruleset/TikTok.list",
    },
    SteamFix: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/${REPO_SLUG}@${REPO_REF}/ruleset/SteamFix.list`,
        path: "./ruleset/SteamFix.list",
    },
    GoogleFCM: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/${REPO_SLUG}@${REPO_REF}/ruleset/FirebaseCloudMessaging.list`,
        path: "./ruleset/FirebaseCloudMessaging.list",
    },
    AdditionalFilter: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/${REPO_SLUG}@${REPO_REF}/ruleset/AdditionalFilter.list`,
        path: "./ruleset/AdditionalFilter.list",
    },
    AdditionalCDNResources: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/${REPO_SLUG}@${REPO_REF}/ruleset/AdditionalCDNResources.list`,
        path: "./ruleset/AdditionalCDNResources.list",
    },
    Crypto: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/${REPO_SLUG}@${REPO_REF}/ruleset/Crypto.list`,
        path: "./ruleset/Crypto.list",
    },
    GFWList: {
        type: "http",
        behavior: "domain",
        format: "yaml",
        interval: 86400,
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt",
        path: "./ruleset/GFWList.yaml",
    },
};
